# Тема “Вычисления с помощью Numpy”

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [48]:
import numpy as np

a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [49]:
print(a)

print(f'Размерность a: {a.ndim}')

print(f'Форма a: {a.shape}')

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность a: 2
Форма a: (5, 2)


In [50]:
mean_a = a.mean(axis=0)

print(f'Средние значения признаков: {mean_a}')

Средние значения признаков: [2.  8.4]


### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [51]:
a_centered = a - mean_a

print(a_centered)

print(f'\nФорма a_centered: {a_centered.shape}')

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]

Форма a_centered: (5, 2)


### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [52]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

print(f'Скалярное произведение столбцов массива a_centered: {a_centered_sp}')

Скалярное произведение столбцов массива a_centered: 8.0


In [53]:
res = a_centered_sp / (a.shape[0] - 1)

print(f'Результат деления a_centered_sp на N-1: {res}')

Результат деления a_centered_sp на N-1: 2.0


### Задание 4*

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [54]:
res2 = np.cov(a.T)

res2[0, 1]

2.0

In [55]:
res2[0, 1] == res

True

### Задание 5**
Необходимо реализовать метод сортировки целых (int) элементов. Метод должен быть реализован без использования “готовых” методов ( sorted, np.sort() ).


In [63]:
a1 = np.random.randint(0, 76, 15)
a1

array([62, 42, 65, 60, 30, 60, 19, 37, 26,  3, 54, 74, 14, 33, 39])

In [58]:
def min_to_max(a):
    a = list(a)
    b = []
    for i in range(len(a.copy())):
        x = min(a)
        b.append(x)
        a.remove(x)
    return np.array(b)

In [64]:
min_to_max(a1)

array([ 3, 14, 19, 26, 30, 33, 37, 39, 42, 54, 60, 60, 62, 65, 74])