### **Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [92]:
import numpy as np

a = np.arange(12, 24)
a, a.size

(array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]), 12)

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [93]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)

a1, a1.ndim, a2, a2.ndim, a3, a3.ndim, a4, a4.ndim, a5, a5.ndim

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 2,
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 2,
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 2,
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 2,
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 2)

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [94]:
a1 = a.reshape(2, -1)
a2 = a.reshape(3, -1)
a3 = a.reshape(-1, 3)
a4 = a.reshape(-1, 2)
a5 = a.reshape(12, -1)

a1, a1.ndim, a2, a2.ndim, a3, a3.ndim, a4, a4.ndim, a5, a5.ndim

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 2,
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 2,
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 2,
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 2,
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]),
 2)

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

В общем смысле можно - это вектор. Однако, в numpy это двумерный массив.

In [95]:
print("Размерность a5: {}".format(a5.ndim))
print("Форма a5: {}".format(a5.shape))

Размерность a5: 2
Форма a5: (12, 1)


Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [96]:
b = np.random.randn(3, 4)
b

array([[ 1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024],
       [-1.72491783, -0.56228753, -1.01283112,  0.31424733]])

In [97]:
b2 = b.flatten()
b2, b2.ndim

(array([ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769,
        -0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753,
        -1.01283112,  0.31424733]),
 1)

In [98]:
b.size == b2.size

True

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [99]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [100]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Не уверен, что на 100% верно понял задание. Но, по моей логике, разница в размерности массивов a и b.

In [101]:
a.ndim == b.ndim

False

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

Массив a имеет x строк и y столбцов.  Массив b имеет $x+1$ строк и y столбцов. Общее количество элементов двух массивов равно 10. Таким образом, 
$$xy+(x+1)y=10$$
$$x=2, y=2$$

In [102]:
a = np.zeros((2, 2))
b = np.ones((2+1, 2))
c = np.vstack((a, b))
a, b, c, c.size

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [103]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
A, At

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]]))

In [104]:
B = A @ At
B, B.shape

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 (4, 4))

In [105]:
np.linalg.det(B)

0.0

Поскольку матрица B вырожденная, найти обратную матрицу для неё **нельзя**.

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [106]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [107]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [108]:
n = int(c.size**0.5)
C = c.reshape(n, n)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [109]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [110]:
print(f'Определитель атрицы D: {np.linalg.det(D)}')
print(f'Ранг атрицы D: {np.linalg.matrix_rank(D)}')
D_inv = np.linalg.inv(D)
print(f'Обратная матрица D_inv:\n{D_inv}')

Определитель атрицы D: -28511999.999999944
Ранг атрицы D: 4
Обратная матрица D_inv:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [115]:
D_inv = np.array(D_inv+1, dtype=int)
D_inv

array([[2, 2, 2, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [2, 1, 2, 1]])

In [112]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])